services:
  - type: web
    name: maeraket-seyada
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://fzmhkozxlixmbmaubkys.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: sb_publishable_62PjGb8ihac7RgeYSCWWdg_bces3jxX
